### ISSUE TITLE
Throw error in an esm environment

### ISSUE THREAD

**Issue by daKmoR** [portabletext/to-html#1]
## Description

I am trying to use

👉  `index.js`

```js
import { toHTML } from "@portabletext/to-html";
```

in an esm project via setting

👉  `package.json`

```js
// ...
"type": "module"
// ...
```

## Expected Behavior

That the import works

## Actual Behavior

An error is thrown

```
import { toHTML } from "@portabletext/to-html";
         ^^^^^^
SyntaxError: Named export 'toHTML' not found. The requested module '@portabletext/to-html' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@portabletext/to-html';
const { toHTML } = pkg;
```

## Suggested solution

This package is not defined as an esm package (e.g. there is no entry in the package.json) therefore any file that is esm needs to end in `*.mjs`.

```diff
  "exports": {
    ".": {
-      "import": "./dist/to-html.esm.js",
+      "import": "./dist/to-html.mjs",
      "require": "./dist/to-html.cjs.js"
    }
  },
```  

Renaming the file solves the issue for this package but then the same issue occurs within `@portabletext/toolkit`

```
import { nestLists, isPortableTextToolkitList, isPortableTextListItemBlock, isPortableTextToolkitSpan, spanToPlainText, isPortableTextBlock, isPortableTextToolkitTextNode, buildMarksTree } from "@portabletext/toolkit";
                                                                                                                                                                            ^^^^^^^^^^^^^^
SyntaxError: Named export 'buildMarksTree' not found. The requested module '@portabletext/toolkit' is a CommonJS module, which may not support all module.exports as named exports.
[...]
```

## Help

What is the best way I can help to resolve this? Would you like me to start an issue/PR on `@portabletext/toolkit` or will you take it from here? 🤔

## Environment

Tested on a Mac with node 16 & 17

**Comment by rexxars** [comment]
Thanks for reporting! This should be fixed in [v1.0.3](https://github.com/portabletext/to-html/releases/tag/v1.0.3)
