### ISSUE TITLE
Any way to use it as CommonJS?

### ISSUE THREAD

**Issue by WebShapedBiz** [portabletext/to-html#62]
Hi guys.
For years now I've been using 11ty SSG and in that period I've created several project templates with all bells and whistles included. Now I'm trying to include Sanity.io as my default headless CMS but it seems that I cannot use EMS modules in my 11ty templates without a huge overhaul and even then I'm not sure about the results.
Is there a CommonJS version of this module that  I can use? Or perhaps a way to use it with the `require()` function?

Thank you for your time and effort.

**Comment by rexxars** [comment]
Certainly - it should work with CommonJS out of the box, since we ship a dual ESM/CommonJS package:

```sh
npm install --save @portabletext/to-html`
```

```js
const {toHTML} = require('@portabletext/to-html')

console.log(
  toHTML(portableTextBlocks, {
    components: {
      /* optional object of custom components to use */
    },
  }),
)
```

**Comment by WebShapedBiz** [comment]
Thank you very much @rexxars for your time and effort, I appreciate it.
