### ISSUE TITLE
From release 2.0.6, import of toHTML appears to Vite as CommonJs, thus fails ES build

### ISSUE THREAD

**Issue by narration-sd** [portabletext/to-html#81]
I was troubleshooting something else, from recent upgrade of Astro, and suddenly this error began appearing., once I also updated all packages using ncu -u.

 It makes no sense, on a quick examination of the @portabletext/to-html package in node_modules, but backing off to @portabletext/to-html@2.0.5 fixes the problem. I note that 2.0.6 and 2.0.7 are very recent, and both will demonstrate this problem.
 
 This is the offending code line:

 `import { toHTML, uriLooksSafe } from "@portabletext/to-html"`
 
 And the error, in an npm build -- needless to say, the proposed fix is also not accurate:
 
 @example/basics:build: 21:34:50 [vite] ✓ built in 15.23s
@example/basics:build: 
@example/basics:build:  generating static routes
@example/basics:build: Named export 'toHTML' not found. The requested module '@portabletext/to-html' is a CommonJS module, which may not support all module.exports as named exports.
@example/basics:build: CommonJS modules can always be imported via the default export, for example using:
@example/basics:build:
@example/basics:build: import pkg from '@portabletext/to-html';
@example/basics:build: const { toHTML, uriLooksSafe } = pkg;
@example/basics:build:
@example/basics:build:   Stack trace:
@example/basics:build:     at ModuleJob._instantiate (node:internal/modules/esm/module_job:132:21)
@example/basics:build:     at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
@example/basics:build:     at async generatePages (file:///C:/vger/projects/astro/sanity-astro-presentation/apps/example/node_modules/astro/dist/core/build/generate.js:164:9)
@example/basics:build:     at async AstroBuilder.build (file:///C:/vger/projects/astro/sanity-astro-presentation/apps/example/node_modules/astro/dist/core/build/index.js:134:5)
@example/basics:build:     at async build (file:///C:/vger/projects/astro/sanity-astro-presentation/apps/example/node_modules/astro/dist/core/build/index.js:46:3)
@example/basics:build: npm ERR! Lifecycle script `build` failed with error: 
@example/basics:build: npm ERR! Error: command failed
@example/basics:build: npm ERR!   in workspace: @example/basics@0.3.0
@example/basics:build: npm ERR!   at location: C:\vger\projects\astro\sanity-astro-presentation\apps\example
@example/basics:build: ERROR: command finished with error: command (C:\vger\projects\astro\sanity-astro-presentation\apps\example) C:\Program Files\nodejs\npm.cmd run build exited (1)
@example/basics#build: command (C:\vger\projects\astro\sanity-astro-presentation\apps\example) C:\Program Files\nodejs\npm.cmd run build exited (1)

**Comment by spacedawwwg** [comment]
Experiencing the same issue

**Comment by rdgomt** [comment]
same here

**Comment by brianphillips** [comment]
I am having the same issue with versions `>= 2.0.6`. I'm no expert on the finer points of ESM but I wonder if it's related to changing how exports are structured in this commit? 02b2d41c7641fee0e2a9378d348b1ad430c9152d

**Comment by stipsan** [comment]
Hey folks, could you test [v2.0.8](https://github.com/portabletext/to-html/releases/tag/v2.0.8) and let us know if it fixes your build problems?

**Comment by narration-sd** [comment]
Hey back, Cody, looking very good here, local dev and netlify deploy.

And when I brought that project up to latest releases, the very welcome click-to-edit visual position sync as back t fine, in Presentation :)

Pretty appreciated work, all of it, thanks

**Comment by stipsan** [comment]
Great to hear! :D
